baseURL = "https://hugeatom.github.io/DianyangDotBlog/"
publishDir = "docs"
title = "dianyang.blog"
theme ="hugo-theme-basic"
languageCode = "en-us"
googleAnalytics = "UA-XXXXXXXXX-X"
enableEmoji = false 
description = "a simple personal blog"

[taxonomies]
  tag = "tags"

[params]
  twitter = "iterateinteract"

[Permalinks]
  post = "posts/:slug"

[[params.menu]]
  name = "posts"
  url = "posts/"

#[[params.menu]]
  #name = "about"
  #url = "about/"
  

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true